export const squeakData = {
    
    squeaks: [ 
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "Today",
            pfp: "./images/mickey.jpg",
            category: "funDealer",
            body: "I am LOVING life today!",
            image: "./images/Steamboat-Willie.webp",
            likes: "1M",
            resqueaks: "500K",
            replies: "10K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "Today",
            pfp: "./images/mickey.jpg",
            category: "funDealer",
            body: "new pfp",
            image: "./images/mickey.jpg",
            likes: "1M",
            resqueaks: "500K",
            replies: "10K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "Today",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "Minnie and I enjoyed a lovely sunset in Toontown. What's your favorite time of day? #SimpleJoys",
            image: "",
            likes: "1M",
            resqueaks: "500K",
            replies: "10K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "01/01/09",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "Minnie and I enjoyed a lovely sunset in Toontown. What's your favorite time of day? #SimpleJoys",
            image: "",
            likes: "1M",
            resqueaks: "500K",
            replies: "10K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "03/15/11",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "Had a quiet day reading comic books in the Clubhouse. What's your favorite comic series? #ComicRelaxation",
            image: "",
            likes: "800K",
            resqueaks: "300K",
            replies: "5K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "07/22/13",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "Visited Clarabelle's bakery for some delicious treats! What's your guilty pleasure dessert? #SweetTooth",
            image: "",
            likes: "1.2M",
            resqueaks: "700K",
            replies: "15K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "11/09/15",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "Caught up with Goofy for a game of checkers. Do you have a favorite board game? #GameTime",
            image: "",
            likes: "900K",
            resqueaks: "400K",
            replies: "8K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "05/06/17",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "Explored new doodle designs for my shorts today. What's your favorite pattern? #FashionFun",
            image: "",
            likes: "1.5M",
            resqueaks: "600K",
            replies: "12K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "08/29/19",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "Took a scenic route through Mickey Park. Nature is truly amazing! #NatureWalk",
            image: "",
            likes: "1.1M",
            resqueaks: "550K",
            replies: "11K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "12/11/21",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "Organized my classic cartoon collection. Which Mickey Mouse cartoon is your all-time favorite? #CartoonNostalgia",
            image: "",
            likes: "1.3M",
            resqueaks: "650K",
            replies: "13K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "02/14/23",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "Helped Donald fix his boat at the dock. Teamwork makes the dream work! #TeamMickey",
            image: "",
            likes: "1.4M",
            resqueaks: "680K",
            replies: "14K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "06/02/22",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "Tried my hand at painting today. What's your favorite form of creative expression? #ArtisticAdventure",
            image: "",
            likes: "1.6M",
            resqueaks: "750K",
            replies: "16K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "01/03/24",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "Found a cozy spot in Mickey Park to enjoy the simple pleasures of life. What brings you tranquility? #PeacefulMoments",
            image: "",
            likes: "1.8M",
            resqueaks: "800K",
            replies: "18K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "01/05/24",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "Just met with @realJamesCameron to discuss Avatars 7 through 21! Really excited to make this happen!",
            image: "",
            likes: "150k",
            resqueaks: "1k",
            replies: "30"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "01/01/24",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "Happy New Year! I hope this year is full of plenty of wonder and joy, ha ha!",
            image: "",
            likes: "10k",
            resqueaks: "500",
            replies: "20"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "06/01/22",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "#Proud to announce that Disney's first openly #LGBT character will appear in Wakanda Forever, coming out this fall!",
            image: "",
            likes: "5k",
            resqueaks: "700k",
            replies: "900k"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "06/02/22",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "#Proud to announce that Disney's first openly #LGBT character will appear in Strange World, coming out this Christmas!",
            image: "",
            likes: "5k",
            resqueaks: "700k",
            replies: "900k"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "06/03/22",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "#Proud to announce that Disney's first openly #LGBT character will appear in Lightyear, coming out this Christmas!",
            image: "",
            likes: "4k",
            resqueaks: "600k",
            replies: "800k"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "06/04/22",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "#Proud to announce that Disney's first openly #LGBT character will appear in Dr. Strange and the Multiverse of Madness, coming soon!",
            image: "",
            likes: "6k",
            resqueaks: "500k",
            replies: "700k"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "06/04/22",
            pfp: "./images/mickey.jpg",
            category: "tame",
            body: "@LunaticEyes Don't worry, they'll have an important role in the story.",
            image: "",
            likes: "7K",
            resqueaks: "800K",
            replies: "10K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "02/03/13",
            pfp: "./images/mickey.jpg",
            category: "animalAbuse",
            body: "Cruella is the only girlboss we need! #CruellaDidNothingWrong",
            image: "[A picture of a coat made out of puppies]",
            likes: "5K",
            resqueaks: "700K",
            replies: "9M"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "01/20/10",
            pfp: "./images/mickey.jpg",
            category: "animalAbuse",
            body: "Currently in Canada, filming our next nature documentary, White Wilderness! #NatureIsBeautiful",
            image: "[A selfie. In the background is a line of Lemmings going off a cliff]",
            likes: "5K",
            resqueaks: "700K",
            replies: "9M"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "03/19/09",
            pfp: "./images/mickey.jpg",
            category: "historicalInaccuracy",
            body: "Man, these protestors in Virginia are so goddamn annoying.",
            image: "",
            likes: "2K",
            resqueaks: "300K",
            replies: "5K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "05/15/23",
            pfp: "./images/mickey.jpg",
            category: "sympathetic",
            body: "@ronDesantis come at me, I have hundreds of high-priced lawyers.",
            image: "",
            likes: "8K",
            resqueaks: "900K",
            replies: "15K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "07/20/15",
            pfp: "./images/mickey.jpg",
            category: "aggression",
            body: "Happy Spring! Time to get this cleaning out of the way! #SpringCleaning",
            image: "[image: Mickey vacuuming up ashes in the Pirates of the Caribbean ride]",
            likes: "4K",
            resqueaks: "500K",
            replies: "5K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "05/10/11",
            pfp: "./images/mickey.jpg",
            category: "lobbying",
            body: "Just got this copyright extension granted, ha ha! #ForAHundredYearsMore",
            image: "[A still from a party in the Mickey Mouse clubhouse. There is a table in the shape of Mickey's head, on top of it lays a pile of stinky cheese.]",
            likes: "15K",
            resqueaks: "1K",
            replies: "100K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "05/10/11",
            pfp: "./images/mickey.jpg",
            category: "lobbying",
            body: "@SansIsMyWaifu I know having important research still locked under copyright is bad, but think about the potential profit loss for a second. That's what the lawyers keep telling me anyways...",
            image: "",
            likes: "6K",
            resqueaks: "700K",
            replies: "8K"
        },
        {
            author: "Mickey Mouse",
            tag: "@MickeyMouseOfficial",
            date: "03/05/09",
            pfp: "./images/mickey.jpg",
            category: "sympathetic",
            body: "@OswaldLuckiestRabbit I miss you....",
            image: "",
            likes: "3K",
            resqueaks: "400K",
            replies: "4K"
        },
        {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "03/05/09",
        pfp: "./images/mickey.jpg",
        category: "sympathetic",
        body: "@OswaldLuckiestRabbit Please respond...",
        image: "",
        likes: "3K",
        resqueaks: "400K",
        replies: "4K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "12/14/17",
        pfp: "./images/mickey.jpg",
        category: "lobbying",
        body: "Matt Groening stopped returning my calls. Jerk...",
        image: "",
        likes: "7K",
        resqueaks: "800K",
        replies: "10K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "06/13/09",
        pfp: "./images/mickey.jpg",
        category: "drugDealing",
        body: "Magic is real",
        image: "",
        likes: "5K",
        resqueaks: "600K",
        replies: "8K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "09/13/11",
        pfp: "./images/mickey.jpg",
        category: "drugDealing",
        body: "Taking a flight!",
        image: "",
        likes: "4K",
        resqueaks: "500K",
        replies: "7K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "02/28/13",
        pfp: "./images/mickey.jpg",
        category: "drugDealing",
        body: "Gonna eat some FINELY aged cheese tonight!",
        image: "",
        likes: "6K",
        resqueaks: "700K",
        replies: "9K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "02/28/13",
        pfp: "./images/mickey.jpg",
        category: "drugDealing",
        body: "Lovin this cheese!",
        image: "",
        likes: "7K",
        resqueaks: "800K",
        replies: "10K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "02/28/13",
        pfp: "./images/mickey.jpg",
        category: "drugDealing",
        body: "Mmmffp cches",
        image: "",
        likes: "5K",
        resqueaks: "600K",
        replies: "8K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "02/28/13",
        pfp: "./images/mickey.jpg",
        category: "drugDealing",
        body: "ccches :D",
        image: "",
        likes: "6K",
        resqueaks: "700K",
        replies: "9K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "03/01/13",
        pfp: "./images/mickey.jpg",
        category: "sympathetic",
        body: "My head hurts :(",
        image: "",
        likes: "3K",
        resqueaks: "400K",
        replies: "5K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "07/08/12",
        pfp: "./images/mickey.jpg",
        category: "aggression",
        body: "Paparazzi outside my house - paparazzi in the ground...",
        image: "",
        likes: "6K",
        resqueaks: "700K",
        replies: "9K"
    },{
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "03/24/18",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "Can't get enough of that spring air! aha",
        image: "",
        likes: "5K",
        resqueaks: "600K",
        replies: "8K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "09/06/17",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "Lovin that winter breeze! So nice when you're in Florida, haha!",
        image: "",
        likes: "4K",
        resqueaks: "500K",
        replies: "7K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "06/30/18",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "All you need to do is believe!",
        image: "",
        likes: "6K",
        resqueaks: "700K",
        replies: "9K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "05/04/19",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "All you need to do is believe!",
        image: "",
        likes: "7K",
        resqueaks: "800K",
        replies: "10K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "04/03/16",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "All you need in life is a bit of magic!",
        image: "",
        likes: "5K",
        resqueaks: "600K",
        replies: "8K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "11/25/20",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "All you need in life is a bit of fun!",
        image: "",
        likes: "6K",
        resqueaks: "700K",
        replies: "9K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "11/21/21",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "All you need in life is a bit of Disney magic!",
        image: "",
        likes: "7K",
        resqueaks: "800K",
        replies: "10K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "10/21/22",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "All you need in life is a bit of Disney Entertainment!",
        image: "",
        likes: "8K",
        resqueaks: "900K",
        replies: "12K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "10/19/23",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "I can't believe that it's been 50 years since 1973, feels like so long ago! Reminds me of my old friend Goofy, what a goofball he was....",
        image: "",
        likes: "9K",
        resqueaks: "1M",
        replies: "15K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "01/01/24",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "Happy new years to all my friends out there!",
        image: "",
        likes: "10K",
        resqueaks: "1.2M",
        replies: "20K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "05/03/19",
        pfp: "./images/mickey.jpg",
        category: "lobbying",
        body: "@CopyrightEnjoyer We're hoping to get parody law abolished next!",
        image: "",
        likes: "7K",
        resqueaks: "800K",
        replies: "12K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "03/11/12",
        pfp: "./images/mickey.jpg",
        category: "sympathetic",
        body: "@MakaiEscapee You can't trust everything the media says about me, ha ha.",
        image: "",
        likes: "6K",
        resqueaks: "700K",
        replies: "10K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "12/25/10",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "Thank you so much for the Christmas gift @GoofiestGoof :heart:",
        image: "",
        likes: "8K",
        resqueaks: "900K",
        replies: "15K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "12/25/10",
        pfp: "./images/mickey.jpg",
        category: "aggressive",
        body: "I don't want to say who but someone I know GOOFED UP Christmas again with a terrible present....",
        image: "",
        likes: "5K",
        resqueaks: "600K",
        replies: "8K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "12/15/09",
        pfp: "./images/mickey.jpg",
        category: "drugDealing",
        body: "drowning in the sauce...",
        image: "",
        likes: "8K",
        resqueaks: "5K",
        replies: "10K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "06/13/14",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "Just wrapped up a fun day at the clubhouse with Minnie and the whole gang!",
        image: "",
        likes: "10K",
        resqueaks: "3K",
        replies: "12K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "05/14/11",
        pfp: "./images/mickey.jpg",
        category: "aggressive",
        body: "Genuinely hate my job with a passion and everyone who works there...",
        image: "",
        likes: "9K",
        resqueaks: "4K",
        replies: "15K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "03/29/20",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "Oh, boy! Did you know that laughter is the best medicine?",
        image: "",
        likes: "12K",
        resqueaks: "5K",
        replies: "18K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "01/06/21",
        pfp: "./images/mickey.jpg",
        category: "lobbying",
        body: "@CNN Reminds me of my visit to the capitol! Man, we sure showed those public domainies!",
        image: "",
        likes: "15K",
        resqueaks: "7K",
        replies: "22K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "05/10/11",
        pfp: "./images/mickey.jpg",
        category: "sympathetic",
        body: "Damn, I was hoping we could hang out in the 'main soon.",
        image: "",
        likes: "14K",
        resqueaks: "8K",
        replies: "20K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "05/10/11",
        pfp: "./images/mickey.jpg",
        category: "sympathetic",
        body: "I know, man. I didn't have much of a say in the",
        image: "",
        likes: "16K",
        resqueaks: "9K",
        replies: "25K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "4/20/15",
        pfp: "./images/mickey.jpg",
        category: "drugDealing",
        body: "Celebrating today with some Stinky Cheese ;)",
        image: "",
        likes: "20K",
        resqueaks: "5K",
        replies: "15K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "4/20/15",
        pfp: "./images/mickey.jpg",
        category: "drugDealing",
        body: "what even are hands?",
        image: "",
        likes: "18K",
        resqueaks: "6K",
        replies: "12K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "4/20/15",
        pfp: "./images/mickey.jpg",
        category: "drugDealing",
        body: "i could really go for handwich right now dude.",
        image: "",
        likes: "16K",
        resqueaks: "7K",
        replies: "14K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "4/20/15",
        pfp: "./images/mickey.jpg",
        category: "drugDealing",
        body: "The Beasts Are Coming.",
        image: "",
        likes: "14K",
        resqueaks: "8K",
        replies: "16K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "4/20/15",
        pfp: "./images/mickey.jpg",
        category: "drugDealing",
        body: "@MichaelEisner seriously dude you gotta bring the Handwich back maaan.",
        image: "",
        likes: "22K",
        resqueaks: "9K",
        replies: "18K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "4/21/15",
        pfp: "./images/mickey.jpg",
        category: "drugDealing",
        body: "Raising funds to help keep Stinky Cheese off the streets!",
        image: "",
        likes: "24K",
        resqueaks: "10K",
        replies: "20K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "9/22/17",
        pfp: "./images/mickey.jpg",
        category: "sympathetic",
        body: "Takin a stroll...",
        image: "",
        likes: "15K",
        resqueaks: "5K",
        replies: "12K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "01/07/21",
        pfp: "./images/mickey.jpg",
        category: "sympathetic",
        body: "[image]",
        image: "",
        likes: "18K",
        resqueaks: "8K",
        replies: "15K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "05/21/09",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "I've been mastering my Shadow Clone Jitsu. That's how I'm able to be at every Disney theme park at the same time.",
        image: "",
        likes: "25K",
        resqueaks: "7K",
        replies: "20K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "08/15/14",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "@RealSteveJobs dude you gotta come visit us at Pixar again sometime!",
        image: "",
        likes: "30K",
        resqueaks: "6K",
        replies: "25K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "08/15/14",
        pfp: "./images/mickey.jpg",
        category: "sympathetic",
        body: "...what do you mean he's dead?",
        image: "",
        likes: "20K",
        resqueaks: "5K",
        replies: "18K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "09/16/18",
        pfp: "./images/mickey.jpg",
        category: "aggressive",
        body: "@Shrek fight me at the Denny's off the interstate, you coward.",
        image: "",
        likes: "15K",
        resqueaks: "10K",
        replies: "12K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "09/16/18",
        pfp: "./images/mickey.jpg",
        category: "aggressive",
        body: "@Shrek say one more thing about any of my company's properties. I dare you.",
        image: "",
        likes: "18K",
        resqueaks: "12K",
        replies: "15K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "11/20/23",
        pfp: "./images/mickey.jpg",
        category: "sympathetic",
        body: "we're gonna pretend we never sold any NFTs",
        image: "",
        likes: "25K",
        resqueaks: "10K",
        replies: "20K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "05/12/16",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "how can our ears be real if our eyes aren't real",
        image: "",
        likes: "22K",
        resqueaks: "8K",
        replies: "18K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "08/11/23",
        pfp: "./images/mickey.jpg",
        category: "sympathetic",
        body: "you ever regret posting something to the internet",
        image: "",
        likes: "28K",
        resqueaks: "7K",
        replies: "25K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "10/11/11",
        pfp: "./images/mickey.jpg",
        category: "subliminalMessaging",
        body: "Visiting this beautiful wildlife sanctuary!",
        image: "",
        likes: "30K",
        resqueaks: "6K",
        replies: "22K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "11/26/09",
        pfp: "./images/mickey.jpg",
        category: "subliminalMessaging",
        body: "Going for a stroll",
        image: "./images/the_real_suicide_mouse.webp",
        likes: "50K",
        resqueaks: "7K",
        replies: "20K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "11/26/16",
        pfp: "./images/mickey.jpg",
        category: "historicalInaccuracy",
        body: "@realDonaldTrump The Roman Empire never existed..",
        image: "",
        likes: "59K",
        resqueaks: "7K",
        replies: "2K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "03/01/17",
        pfp: "./images/mickey.jpg",
        category: "historicalInaccuracy",
        body: "@MinnieMouse This is so not true, just like the moon landings..",
        image: "",
        likes: "59K",
        resqueaks: "7K",
        replies: "2K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "03/01/14",
        pfp: "./images/mickey.jpg",
        category: "historicalInaccuracy",
        body: "Stop making stuff up. I did it. Me. Alone. I built the Pyramids. not slaves, not aliens. Me.",
        image: "",
        likes: "100K",
        resqueaks: "7K",
        replies: "2K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "06/01/13",
        pfp: "./images/mickey.jpg",
        category: "subliminalMessaging",
        body: "Stop looking for deeper meaning in things!",
        image: "",
        likes: "MESSAGE",
        resqueaks: "LIMINAL",
        replies: "SUB"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "06/01/16",
        pfp: "./images/mickey.jpg",
        category: "animalAbuse",
        body: "Pulling the cows tail Ahahaha",
        image: "./images/animal_abuse.jpg",
        likes: "13K",
        resqueaks: "3K",
        replies: "2K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "03/11/22",
        pfp: "./images/mickey.jpg",
        category: "animalAbuse",
        body: "Getting Milk!",
        image: "./images/milk.jpg",
        likes: "19K",
        resqueaks: "23K",
        replies: "17K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "03/11/20",
        pfp: "./images/mickey.jpg",
        category: "aggression",
        body: "There's an anger inside of me. I lose it far too often..",
        image: "./images/anger.jpg",
        likes: "23K",
        resqueaks: "20K",
        replies: "10K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "04/21/11",
        pfp: "./images/mickey.jpg",
        category: "drugDealing",
        body: "Cops caught me with some extra stinky cheese last night.. still keeping it chili! @NYPD",
        image: "./images/caught.jpg",
        likes: "4M",
        resqueaks: "100K",
        replies: "90K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "01/01/12",
        pfp: "./images/mickey.jpg",
        category: "historicalInaccuracy",
        body: "Welp, this is it. 2012. I can't believe that the world is ending..",
        image: "./images/end.jpg",
        likes: "1M",
        resqueaks: "140K",
        replies: "120K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "01/04/09",
        pfp: "./images/mickey.jpg",
        category: "animalAbuse",
        body: "Hehehehehehe 'cat and mouse' WHO'S THE CAT NOW???",
        image: "./images/cat.jpg",
        likes: "500K",
        resqueaks: "160K",
        replies: "190K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "03/17/11",
        pfp: "./images/mickey.jpg",
        category: "drugDealing",
        body: "My Face When someone says there's sauce",
        image: "./images/sauce.jpg",
        likes: "90K",
        resqueaks: "30K",
        replies: "19K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "07/17/19",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "Sometimes you have to leave in order to grow..",
        image: "./images/leaving.webp",
        likes: "190K",
        resqueaks: "130K",
        replies: "119K"
    },
    {
        author: "Mickey Mouse",
        tag: "@MickeyMouseOfficial",
        date: "04/11/14",
        pfp: "./images/mickey.jpg",
        category: "tame",
        body: "If you have multiple personality disorder, and you date multiple of your personalities, is that polyamory? Asking for another personality",
        image: "",
        likes: "1M",
        resqueaks: "900K",
        replies: "3M"
    }

    ]
    
}